### ISSUE TITLE
State of multi-process and virtual memory support

### ISSUE THREAD

**Issue by akkartik** [ozkl/soso#3]
It looks like `shell` loads user processes synchronously (`execute`). And it looks like there's no virtual memory, and all user processes load at physical address 0x40000000. The `shell` process runs in kernel space and loads commands one at a time in user space. Therefore, it looks like any user process that forked and loaded another binary (that was compiled with the packaged libc and its `_start`) would have its code segment clobbered. Is all this accurate?

(Not intended as criticism. I just want to check my understanding.)

**Comment by ozkl** [comment]
Multi-process and virtual memory are supported already. Shell runs in usermode. It executes a process and waits it to complete. You can run another process at the same time by using other shells (try ALT+F2). You can also kill a process in ther shell using "kill pid". 0x40000000 is the virtual address. All running processes are starting at 0x40000000 because it is a virtual memory address mapped to somewhere in real address space.

**Comment by akkartik** [comment]
I've been meaning to ask about the multiple ttys. I wasn't sure how to
switch between them. I tried Alt-F2 like in Linux, but without luck. Does
it work for you on Qemu? Here's the command I use:

$ qemu-system-i386 -cdrom soso.iso

I'm on a Mac. Maybe I should try it on Linux.

**Comment by ozkl** [comment]
Yes it works on Linux QEMU. I think QEMU needs to the capture mouse in order to receive ALT key. At least it works this way on my machine :) So click inside QEMU window and then give it a try.

Yeah, the command you use seems fine.
